[package]
name = "ghdepup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
hyper-tls = { version = "0.5.0" }
tokio = { version = "1", features = ["full", "rt", "macros"] }
serde = { version = "1.0" }
serde_json = { version = "1.0", features = ["std"] }
itertools = { version = "0.11.0" }
semver =  { version = "1.0.18" }
toml = { version = "0.8.0", features = ["parse", "display"] }