HYPER_GH_PROJECT="hyperium/hyper"
HYPER_GH_TAG_PREFIX="v"
HYPER_GH_VERSION_REQ=">=0.14, <1"
HYPER_GH_VERSION="0.14.26"

HYPER_TLS_GH_PROJECT="hyperium/hyper-tls"
HYPER_TLS_GH_TAG_PREFIX="v"
HYPER_TLS_GH_VERSION_REQ=">=0.5"
HYPER_TLS_GH_VERSION="0.5.0"
