HYPER_CRATE_NAME="hyper"
HYPER_GH_PROJECT="hyperium/hyper"
HYPER_GH_TAG_PREFIX="v"
HYPER_GH_VERSION_REQ=">=0.14, <1"

HYPER_TLS_CRATE_NAME="hyper-tls"
HYPER_TLS_GH_PROJECT="hyperium/hyper-tls"
HYPER_TLS_GH_TAG_PREFIX="v"
HYPER_TLS_GH_VERSION_REQ=">=0.5, <0.6"

TOKIO_CRATE_NAME="tokio"
TOKIO_GH_PROJECT="tokio-rs/tokio"
TOKIO_GH_TAG_PREFIX="tokio-"
TOKIO_GH_VERSION_REQ=">=1, <2"

SERDE_CRATE_NAME="serde"
SERDE_GH_PROJECT="serde-rs/serde"
SERDE_GH_TAG_PREFIX="v"
SERDE_GH_VERSION_REQ=">=1, <2"

SERDE_JSON_CRATE_NAME="serde-json"
SERDE_JSON_GH_PROJECT="serde-rs/json"
SERDE_JSON_GH_TAG_PREFIX="v"
SERDE_JSON_GH_VERSION_REQ=">=1, <2"

ITERTOOLS_CRATE_NAME="itertools"
ITERTOOLS_GH_PROJECT="rust-itertools/itertools"
ITERTOOLS_GH_TAG_PREFIX="v"
ITERTOOLS_GH_VERSION_REQ=">=0.11, <1"

SEMVER_CRATE_NAME="semver"
SEMVER_GH_PROJECT="dtolnay/semver"
SEMVER_GH_TAG_PREFIX=""
SEMVER_GH_VERSION_REQ=">=1, <2"

TOML_CRATE_NAME="toml"
TOML_GH_PROJECT="toml-rs/toml"
TOML_GH_TAG_PREFIX="toml-v"
TOML_GH_VERSION_REQ=">=0.8, <1"

FUTURES_CRATE_NAME="futures"
FUTURES_GH_PROJECT="rust-lang/futures-rs"
FUTURES_GH_TAG_PREFIX=""
FUTURES_GH_VERSION_REQ=">=0.3, <1"
