FUTURES_GH_VERSION="0.3.30"
HYPER_GH_VERSION="0.14.30"
HYPER_TLS_GH_VERSION="0.5.0"
ITERTOOLS_GH_VERSION="0.13.0"
RUSTLANG_GH_VERSION="1.80.1"
SEMVER_GH_VERSION="1.0.23"
SERDE_GH_VERSION="1.0.205"
SERDE_JSON_GH_VERSION="1.0.122"
TOKIO_GH_VERSION="1.39.2"
TOML_GH_VERSION="0.8.19"
