FUTURES_GH_VERSION=""
HYPER_GH_VERSION="0.14.29"
HYPER_TLS_GH_VERSION="0.6.0"
ITERTOOLS_GH_VERSION="0.13.0"
SEMVER_GH_VERSION=""
SERDE_GH_VERSION="1.0.203"
SERDE_JSON_GH_VERSION="1.0.117"
TOKIO_GH_VERSION=""
TOML_GH_VERSION="0.22.14"
