FUTURES_GH_VERSION="0.3.30"
HYPER_GH_VERSION="0.14.29"
HYPER_TLS_GH_VERSION="0.5.0"
ITERTOOLS_GH_VERSION="0.13.0"
SEMVER_GH_VERSION="1.0.23"
SERDE_GH_VERSION="1.0.203"
SERDE_JSON_GH_VERSION="1.0.117"
TOKIO_GH_VERSION="1.38.0"
TOML_GH_VERSION="0.8.14"
