[package]
name = "selfupdate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = { version = "0.8.0", features = ["parse", "display"] }
serde = { version = "1.0" }