name: selfupdate check
run-name: selfupdate 🚀 check
on: [push]
jobs:
  Selfupdate-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: selfupdate
        uses: ./.github/actions/selfupdate/
      - run: echo "🍏 This job's status is ${{ job.status }}."
