name: selfupdate check
run-name: selfupdate 🚀 check
on: [push]
jobs:
  Selfupdate-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: rust build
        uses: ./.github/actions/rustbuild-build-action/
      - run: echo "🍏 This job's status is ${{ job.status }}."
