name: 🔍 merge checks
run-name: 🔍 merge checks
on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  merge_check:
    name: 🔍 merge checks
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Check out repository code
        uses: actions/checkout@v4
      - name: ⏬ Install stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: 🛠 Build ghdepup
        run: cargo build
      - name: 🧪 Test ghdepup
        run: cargo test
      - name: 🛠 Build selfupdate
        run: cargo build
        working-directory: ./.github/actions/selfupdate
      - name: 🧪 Test selfupdate
        run: cargo test
        working-directory: ./.github/actions/selfupdate
